version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: o1_db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "9640715869"
    ports:
      - "9640:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d app_db"]
      interval: 5s
      timeout: 3s
      retries: 15

  backend:
    image: doc9640/o1-backend:latest
    container_name: o1_backend
    env_file:
      - ./backend/.env.docker
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:9640715869@db:5432/app_db}
      HOST: 0.0.0.0
      PORT: 8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: doc9640/o1-frontend:latest
    container_name: o1_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  dbdata:
